# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/klikli-dev/occultism/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="occultism" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Occultism" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://raw.githubusercontent.com/klikli-dev/occultism/meta/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/occultism" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="occultism.png" #optional
# A text field displayed in the mod UI
credits="""See https://github.com/klikli-dev/occultism#licensing""" #optional
# A text field displayed in the mod UI
authors="Kli Kli" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''A magic mod inspired by the world of Jonathan Stroud's Bartimaeus. With the help of occult rituals players can summon entities from the "Other Side" to perform magic.'''


[[dependencies.occultism]]
    modId = "modonomicon"
    mandatory = true
    versionRange = "[1.18.2-1.8.0,)"
    side = "BOTH"


[[dependencies.occultism]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.18.1-61,)"
    side="BOTH"

[[dependencies.occultism]]
    modId="curios"
    mandatory=true
    versionRange="[1.18-5.0.2.1,)"
    side="BOTH"

[[dependencies.occultism]]
    modId="geckolib3"
    mandatory=true
    versionRange="[1.18-3.0.3,)"
    side="BOTH"

[[dependencies.occultism]]
    modId="jei"
    mandatory=false
    versionRange="[1.18-9.0.0.40,)"
    side="BOTH"

[[dependencies.occultism]]
    modId="forge"
    mandatory=false
    versionRange="[40.0.18,)"
    side="BOTH"
