name: Build and Publish

on:
  push:
    tags:
      - 'alpha/v**'
      - 'beta/v**'
      - 'release/v**'
      - 'test/v**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk
          architecture: x64
      - name: Get release type from github tag
        id: get_release_type
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.RELEASE_NOTES_TOKEN }}
          result-encoding: string
          script: |
            return '${{ github.ref }}'.match(/refs\/tags\/(.*)\/v((.*)-(.*))/)[1];
      - name: Get file version from tag
        id: get_version
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.RELEASE_NOTES_TOKEN }}
          result-encoding: string
          script: |
            return '${{ github.ref }}'.match(/refs\/tags\/(.*)\/v((.*)-(.*))/)[4];
      - name: Get main mc version from tag
        id: get_mc_version
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.RELEASE_NOTES_TOKEN }}
          result-encoding: string
          script: |
            return '${{ github.ref }}'.match(/refs\/tags\/(.*)\/v((.*)-(.*))/)[3];
      - name: "Build"
        uses: eskatos/gradle-command-action@v1
        env:
          VERSION: ${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        with:
          arguments: build --max-workers 1
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_NOTES_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: occultism-${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}-${{ steps.get_release_type.outputs.result }}
          body: |
            [[Automated Build]]
            ## Changelog
            [${{ steps.get_version.outputs.result }}](https://github.com/klikli-dev/occultism/wiki/${{ steps.get_version.outputs.result }})
          draft: false
          prerelease: false
      - name: Upload release asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_NOTES_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/occultism-${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}.jar
          asset_name: occultism-${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}-${{ steps.get_release_type.outputs.result }}.jar
          asset_content_type: application/java-archive
      - name: Upload to Curseforge
        id: curseforge
        uses: itsmeow/curseforge-upload@master
        if: ${{ steps.get_release_type.outputs.result }} != "test"
        with:
          token: ${{ secrets.CURSEFORGE_API_KEY }}
          project_id: 361026
          game_endpoint: minecraft
          file_path: ./build/libs/occultism-${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}.jar
          changelog: |-
            [Automated Build]
            Find changes at https://github.com/klikli-dev/occultism/releases
          display_name: occultism-${{ steps.get_version.outputs.result }}.jar
          game_versions: Forge,1.16.2,1.16.3,1.16.4,1.16.5,${{ steps.get_mc_version.outputs.result }}
          release_type: ${{ steps.get_release_type.outputs.result }}
          relations: patchouli:requiredDependency
#      - name: Upload to Curseforge via Cursegradle
#        id: curseforge
#        if: ${{ steps.get_release_type.outputs.result }} != "test"
#        run: ./gradlew curseforge
#        env:
#          VERSION: ${{ steps.get_version.outputs.result }}
#          MC_VERSION: ${{ steps.get_mc_version.outputs.result }}
#          RELEASE_TYPE: ${{ steps.get_release_type.outputs.result }}
#          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}